---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ provision_apt_packages }}"
  become: true
