---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Update existing packages
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
  become: true

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ provision_apt_packages }}"
  become: true
