---
- name: Install the tmux configuration
  ansible.builtin.command: tmux/install.sh
  args:
    chdir: "{{ provision_code_path }}/{{ provision_github_org }}/dotfiles"
    creates: "/home/{{ provision_user }}/.tmux.conf"
  become: false

- name: Install the bash aliases
  ansible.builtin.command: bash/install.sh
  args:
    chdir: "{{ provision_code_path }}/{{ provision_github_org }}/dotfiles"
    creates: "/home/{{ provision_user }}/.bash_aliases"
  become: false
