# The packages we want to install using apt
provision_apt_packages:
  - "vim"
  - "tmux"

# The user created on the PI, which is linked to user on host
provision_user: "{{ lookup('ansible.builtin.env', 'USER') }}"

# Where the SSH key will be generated (Means we can have a silent generation)
provision_ssh_key_path: "/home/{{ provision_user }}/.ssh/id_rsa"
